wandb_version: 1

data:
  desc: null
  value:
    step: 50
    batch_size: 256
    seq_length: 150
model:
  desc: null
  value:
    fc:
      dropout: 0.3629351856326178
      inner_dim: 50
    encoder:
      dropout: 0.505816000972691
      activation: gelu
      layer_norm_eps: 0.004468593133490127
    embedding:
      in_channels: 1
      out_channels: 25
    num_layers: 2
train:
  desc: null
  value:
    lr: 0.0006345611256400737
    n_epoch: 30
    optimizer: adam
    scheduler_config:
      type: null
random_state:
  desc: null
  value: 42
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710256959.814442
    t:
      1:
      - 1
      - 5
      - 10
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 10
      - 11
      - 49
      - 53
      - 55
      3:
      - 15
      - 16
      - 23
      4: 3.11.5
      5: 0.16.3
      6: 4.37.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
