wandb_version: 1

model:
  desc: null
  value:
    lstm:
      input_dim: 500
      hidden_dim: 100
      num_layers: 2
    fc:
      fc_dim: 50
      dropout: 0
train:
  desc: null
  value:
    optimizer: adam
    lr: 0.0003
    n_epoch: 20
data:
  desc: null
  value:
    seq_length: 500
    step: 25
random_state:
  desc: null
  value: 42
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710243546.501871
    t:
      1:
      - 1
      - 5
      - 10
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 10
      - 11
      - 49
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.5
      5: 0.16.3
      6: 4.37.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
